import { NextRequest, NextResponse } from "next/server";
import { adminAuth, adminDb } from "@/lib/firebase-admin";
import { linkEmployeeToUser, getEmployeeProfile } from "@/lib/firestore/hr";
import { serverTimestamp } from "firebase/firestore";

// POST /api/hr/grant-access - Grant CRM access to an employee
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { employeeId, email, role, password } = body as {
      employeeId: string;
      email: string;
      role: string;
      password?: string;
    };

    if (!employeeId || !email || !role) {
      return NextResponse.json(
        { error: "Missing required fields: employeeId, email, role" },
        { status: 400 }
      );
    }

    // Firebase Auth requires a minimum of 6 characters
    if (password && password.length < 6) {
      return NextResponse.json(
        { error: "Password must be at least 6 characters." },
        { status: 400 }
      );
    }

    // Verify employee exists
    const employeeResult = await getEmployeeProfile(employeeId);
    if (employeeResult.error || !employeeResult.employee) {
      return NextResponse.json(
        { error: "Employee not found" },
        { status: 404 }
      );
    }

    const employee = employeeResult.employee;

    // Check if employee already has CRM access
    if (employee.userId) {
      return NextResponse.json(
        { error: "Employee already has CRM access" },
        { status: 400 }
      );
    }

    // Generate password if not provided
    const userPassword =
      password ||
      Array.from({ length: 12 }, () =>
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%"[
          Math.floor(Math.random() * 66)
        ]
      ).join("");

    // Create Firebase Auth user
    let userRecord;
    try {
      userRecord = await adminAuth.createUser({
        email,
        password: userPassword,
        displayName: employee.displayName,
        emailVerified: false,
      });
    } catch (error: any) {
      // User might already exist
      if (error.code === "auth/email-already-exists") {
        // Try to get existing user
        try {
          const existingUser = await adminAuth.getUserByEmail(email);
          userRecord = existingUser;
        } catch {
          return NextResponse.json(
            { error: "Email already exists but user not found" },
            { status: 400 }
          );
        }
      } else {
        return NextResponse.json(
          { error: `Failed to create auth user: ${error.message}` },
          { status: 500 }
        );
      }
    }

    // Create User document in Firestore
    const userDocRef = adminDb.collection("users").doc(userRecord.uid);
    await userDocRef.set({
      uid: userRecord.uid,
      email: userRecord.email,
      displayName: employee.displayName,
      firstName: employee.firstName || "",
      lastName: employee.lastName || "",
      photoURL: employee.photoURL || null,
      role: role,
      employeeId: employeeId,
      isActive: true,
      isFirstLogin: true,
      status: "active",
      createdAt: serverTimestamp(),
      createdBy: "system", // Could be the current admin's uid
      lastLoginAt: serverTimestamp(),
    });

    // Link employee to user
    await linkEmployeeToUser(employeeId, userRecord.uid);

    // Set custom claims for role
    await adminAuth.setCustomUserClaims(userRecord.uid, { role });

    return NextResponse.json({
      success: true,
      uid: userRecord.uid,
      email: userRecord.email,
      autoGeneratedPassword: !password,
      message: password
        ? "User created successfully"
        : "User created successfully. Password was auto-generated.",
    });
  } catch (error: any) {
    console.error("Error granting CRM access:", error);
    return NextResponse.json(
      { error: "Failed to grant CRM access", details: error.message },
      { status: 500 }
    );
  }
}
